"""dummy-base-schema

Revision ID: 13cb865cb540
Revises:
Create Date: 2021-01-13 22:33:02.359807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13cb865cb540"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dummy_description"), "dummy", ["description"], unique=False
    )
    op.create_index(op.f("ix_dummy_id"), "dummy", ["id"], unique=False)
    op.create_index(op.f("ix_dummy_title"), "dummy", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dummy_title"), table_name="dummy")
    op.drop_index(op.f("ix_dummy_id"), table_name="dummy")
    op.drop_index(op.f("ix_dummy_description"), table_name="dummy")
    op.drop_table("dummy")
    # ### end Alembic commands ###
